<script lang="ts">
  let{data}=$props();
  let featured=$derived(data.page===1?(data.posts.find((p:any)=>p.featured)||data.posts[0]):undefined);
  let remaining=$derived(data.posts.filter((p:any)=>p.id!==featured?.id));
  function href(page:number,category=data.activeCategory,query=data.query){const params=new URLSearchParams();if(category)params.set('category',category);if(query)params.set('q',query);if(page>1)params.set('page',String(page));const value=params.toString();return value?`/blog?${value}`:'/blog';}
</script>
<svelte:head><title>{data.appearance.blogName}｜文章与随笔</title><meta name="description" content={data.appearance.blogDescription} /><link rel="canonical" href={`${data.origin}/blog`} /><meta property="og:type" content="website" /><meta property="og:title" content={`${data.appearance.blogName}｜文章与随笔`} /><meta property="og:description" content={data.appearance.blogDescription} /><meta property="og:url" content={`${data.origin}/blog`} /><meta property="og:image" content={`${data.origin}/og.png`} /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content={data.appearance.blogName} /><meta name="twitter:description" content={data.appearance.blogDescription} /><meta name="twitter:image" content={`${data.origin}/og.png`} /></svelte:head>
<main class="blog shell">
  <section class="blog-hero"><div><p class="eyebrow">TWILIGHT NOTES</p><h1>{data.appearance.blogName}</h1><p>{data.appearance.blogDescription}</p></div><div class="blog-count"><b>{data.total}</b><span>篇文章{data.query?'匹配搜索':data.activeCategory?'符合当前分类':''}</span></div></section>
  <form class="blog-search" method="GET"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></svg><input name="q" value={data.query} placeholder="搜索标题和正文" aria-label="搜索博客文章" />{#if data.activeCategory}<input type="hidden" name="category" value={data.activeCategory}/>{/if}<button>搜索</button></form>
  <div class="blog-layout"><div class="blog-stream">
    {#if featured}<a class="featured-post" href={`/blog/${featured.slug}`}><div class="cover">{#if featured.cover}<img class="cover-image" src={featured.cover} alt={`${featured.title}封面`} width="1200" height="675" />{/if}<span>FEATURED · {featured.categoryName||'随笔'}</span><b>{featured.title}</b></div><div><time>{new Date(featured.publishedAt).toLocaleDateString('zh-CN')}</time><h2>{featured.title}</h2><p>{featured.excerpt}</p><strong>阅读全文 →</strong></div></a>{/if}
    <section class="post-section"><div class="section-title"><div><p class="eyebrow">LATEST NOTES</p><h2>{data.query?`“${data.query}”的结果`:data.activeCategory?(data.categories.find((c:any)=>c.slug===data.activeCategory)?.name||'分类文章'):'最近写下'}</h2></div></div>{#if remaining.length}<div class="post-cards">{#each remaining as post}<a href={`/blog/${post.slug}`}><div><span class="post-category" style={`--category-color:${data.categories.find((c:any)=>c.slug===post.categorySlug)?.color||'var(--brand)'}`}>{post.categoryName||'随笔'}</span><time>{new Date(post.publishedAt).toLocaleDateString('zh-CN')}</time></div><h3>{post.title}</h3><p>{post.excerpt}</p><strong>继续阅读 <span>→</span></strong></a>{/each}</div>{:else}<div class="empty compact-empty"><b>{featured?'更多文章正在慢慢写下':'没有找到文章'}</b><span>{featured?'新的折腾、思考与片段会继续出现在这里。':'试试其他关键词或分类。'}</span></div>{/if}</section>
    {#if data.pageCount>1}<nav class="pagination" aria-label="博客分页"><a class:disabled={data.page===1} aria-disabled={data.page===1} href={href(data.page-1)}>上一页</a><span>第 {data.page} / {data.pageCount} 页</span><a class:disabled={data.page===data.pageCount} aria-disabled={data.page===data.pageCount} href={href(data.page+1)}>下一页</a></nav>{/if}
  </div><aside class="blog-sidebar">
    <section class="side-panel"><p class="eyebrow">CATEGORIES</p><h2>文章分类</h2><nav class="post-categories"><a class:active={!data.activeCategory} href={href(1,'')}><span>全部文章</span><b>{data.categories.reduce((sum:number,item:any)=>sum+Number(item.postCount),0)}</b></a>{#each data.categories as category}<a class:active={data.activeCategory===category.slug} href={href(1,category.slug)}><i style={`background:${category.color}`}></i><span>{category.name}</span><b>{category.postCount}</b></a>{/each}</nav></section>
    <section class="side-panel"><p class="eyebrow">WORD CLOUD</p><h2>文字云</h2><div class="word-cloud">{#each data.cloud as item}<a class={`weight-${item.weight}`} href={href(1,'',item.word)} title={`搜索：${item.word}（出现 ${item.count} 次）`}>{item.word}</a>{/each}</div><small>点击词语即可搜索全部已发布文章</small></section>
    <section class="reader-invite"><span>暮</span><div><b>加入讨论</b><p>登录后评论会直接展示，也可以管理自己的留言。</p><a href={data.user?'/account':'/account/register'}>{data.user?'查看我的账号':'创建读者账号'} →</a></div></section>
  </aside></div>
</main>
