<script lang="ts">let{data}=$props();let featured=$derived(data.posts.find((p:any)=>p.featured)||data.posts[0]);let remaining=$derived(data.posts.filter((p:any)=>p.id!==featured?.id));</script>
<svelte:head><title>{data.appearance.blogName}｜文章与随笔</title><meta name="description" content="记录技术折腾、思考和那些值得慢慢写下来的事情。" /></svelte:head>
<main class="blog shell">
  <section class="blog-hero"><div><p class="eyebrow">TWILIGHT NOTES</p><h1>{data.appearance.blogName}</h1><p>记录折腾、思考和那些值得慢慢写下来的事情。</p></div><div class="blog-count"><b>{data.posts.length}</b><span>篇文章{data.activeCategory?'符合当前分类':''}</span></div></section>
  <div class="blog-layout"><div class="blog-stream">
    {#if featured}<a class="featured-post" href={`/blog/${featured.slug}`}><div class="cover" style={featured.cover?`background-image:url('${featured.cover}')`:''}><span>FEATURED · {featured.categoryName||'随笔'}</span><b>{featured.title}</b></div><div><time>{new Date(featured.publishedAt).toLocaleDateString('zh-CN')}</time><h2>{featured.title}</h2><p>{featured.excerpt}</p><strong>阅读全文 →</strong></div></a>{/if}
    <section class="post-section"><div class="section-title"><div><p class="eyebrow">LATEST NOTES</p><h2>{data.activeCategory?(data.categories.find((c:any)=>c.slug===data.activeCategory)?.name||'分类文章'):'最近写下'}</h2></div></div>{#if remaining.length}<div class="post-cards">{#each remaining as post}<a href={`/blog/${post.slug}`}><div><span class="post-category" style={`--category-color:${data.categories.find((c:any)=>c.slug===post.categorySlug)?.color||'var(--brand)'}`}>{post.categoryName||'随笔'}</span><time>{new Date(post.publishedAt).toLocaleDateString('zh-CN')}</time></div><h3>{post.title}</h3><p>{post.excerpt}</p><strong>继续阅读 <span>→</span></strong></a>{/each}</div>{:else}<div class="empty compact-empty"><b>{featured?'更多文章正在慢慢写下':'这个分类暂时还没有文章'}</b><span>{featured?'新的折腾、思考与片段会继续出现在这里。':'可以换个分类看看，或者过些时候再来。'}</span></div>{/if}</section>
  </div><aside class="blog-sidebar">
    <section class="side-panel"><p class="eyebrow">CATEGORIES</p><h2>文章分类</h2><nav class="post-categories"><a class:active={!data.activeCategory} href="/blog"><span>全部文章</span><b>{data.categories.reduce((sum:number,item:any)=>sum+Number(item.postCount),0)}</b></a>{#each data.categories as category}<a class:active={data.activeCategory===category.slug} href={`/blog?category=${category.slug}`}><i style={`background:${category.color}`}></i><span>{category.name}</span><b>{category.postCount}</b></a>{/each}</nav></section>
    <section class="side-panel"><p class="eyebrow">WORD CLOUD</p><h2>文字云</h2><div class="word-cloud">{#each data.cloud as item}<span class={`weight-${item.weight}`} title={`出现 ${item.count} 次`}>{item.word}</span>{/each}</div><small>根据所有已发布文章的标题与正文自动生成</small></section>
    <section class="reader-invite"><span>暮</span><div><b>加入讨论</b><p>登录后评论会直接展示，也可以管理自己的留言。</p><a href={data.user?'/account':'/account/register'}>{data.user?'查看我的账号':'创建读者账号'} →</a></div></section>
  </aside></div>
</main>
